### PR TITLE
Refactor to extract icon() method.

### PR DESCRIPTION
**Pull request by dereuromark**
Also, can you please merge

```
https://github.com/drmonkeyninja/cakephp-social-share/tree/3.x
```

It contains the 3.x array syntax.
Thx :)

### CODE REVIEW

**Comment by drmonkeyninja** [comment]
Thanks Mark. I've merged your pull request but not sure I follow what you are asking me to merge in for the array syntax. The array syntax in the master branch already looks correct to me. What am I missing?

**Comment by dereuromark** [comment]
See https://github.com/drmonkeyninja/cakephp-social-share/compare/3.x (the 3.x branch is one commit ahead).

**Comment by drmonkeyninja** [comment]
Not sure what happened there as those changes were already in the master branch. It has been properly merged now though. Thanks.

**Comment by dereuromark** [comment]
:+1:

**Pull request merged**
