### PR TITLE
Add whatsapp.

### LINKED ISSUE #3: Whatsapp
Hi,

can you add whatsapp? Should be very easy:
https://github.com/heiseonline/shariff/blob/master/src/js/services/whatsapp.js

Thanks,
Marco

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/drmonkeyninja/cakephp-social-share/issues/3

### CODE REVIEW

**Comment by dereuromark** [comment]
You should enable travis (for PRs).

**Comment by drmonkeyninja** [comment]
Looks good @dereuromark, just one question: I'm not too familiar with whatsapp, I've noticed people implying you need to include `data-action="share/whatsapp/share"` on the anchor tag. Do you know if this is required, or will it work with just the whatsapp protocol/URL you've included?

**Comment by drmonkeyninja** [comment]
I keep meaning to look into setting up travis. I will investigate. :smile:

**Comment by dereuromark** [comment]
I looked into some example posts around it, and they all didn't.
E.g. http://www.whatsapp.com/faq/en/android/28000012

What resources did you find about it that imply it?

**Comment by dereuromark** [comment]
I think using the data attribute is an alternative form, from the looks:

```
<a href="whatsapp://send" data-text="Take a look at this awesome website:" data-href="" 
   ...>Share</a>
```

instead of 

```
<a href="whatsapp://send?text={text}%20{url}">Share</a>
```

But it wouldn't hurt to add `data-action="share/whatsapp/share"` either. To be sure.

**Comment by drmonkeyninja** [comment]
Seeing as the official website doesn't use data-attributes I guess it means this URL is fine. I've merged in your pull request to the main branch. Thanks for the contribution.

**Pull request merged**
